/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsUploadRouteImport } from './routes/leads/upload'
import { Route as ApiLeadsUploadRouteImport } from './routes/api/leads/upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiLeadsDocumentsDocumentIdStatusRouteImport } from './routes/api/leads/documents/$documentId/status'
import { Route as ApiLeadsDocumentsDocumentIdRetryRouteImport } from './routes/api/leads/documents/$documentId/retry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsUploadRoute = LeadsUploadRouteImport.update({
  id: '/leads/upload',
  path: '/leads/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsUploadRoute = ApiLeadsUploadRouteImport.update({
  id: '/api/leads/upload',
  path: '/api/leads/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsDocumentsDocumentIdStatusRoute =
  ApiLeadsDocumentsDocumentIdStatusRouteImport.update({
    id: '/api/leads/documents/$documentId/status',
    path: '/api/leads/documents/$documentId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLeadsDocumentsDocumentIdRetryRoute =
  ApiLeadsDocumentsDocumentIdRetryRouteImport.update({
    id: '/api/leads/documents/$documentId/retry',
    path: '/api/leads/documents/$documentId/retry',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leads/upload': typeof LeadsUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leads/upload': typeof ApiLeadsUploadRoute
  '/api/leads/documents/$documentId/retry': typeof ApiLeadsDocumentsDocumentIdRetryRoute
  '/api/leads/documents/$documentId/status': typeof ApiLeadsDocumentsDocumentIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leads/upload': typeof LeadsUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leads/upload': typeof ApiLeadsUploadRoute
  '/api/leads/documents/$documentId/retry': typeof ApiLeadsDocumentsDocumentIdRetryRoute
  '/api/leads/documents/$documentId/status': typeof ApiLeadsDocumentsDocumentIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leads/upload': typeof LeadsUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/leads/upload': typeof ApiLeadsUploadRoute
  '/api/leads/documents/$documentId/retry': typeof ApiLeadsDocumentsDocumentIdRetryRoute
  '/api/leads/documents/$documentId/status': typeof ApiLeadsDocumentsDocumentIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leads/upload'
    | '/api/auth/$'
    | '/api/leads/upload'
    | '/api/leads/documents/$documentId/retry'
    | '/api/leads/documents/$documentId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leads/upload'
    | '/api/auth/$'
    | '/api/leads/upload'
    | '/api/leads/documents/$documentId/retry'
    | '/api/leads/documents/$documentId/status'
  id:
    | '__root__'
    | '/'
    | '/leads/upload'
    | '/api/auth/$'
    | '/api/leads/upload'
    | '/api/leads/documents/$documentId/retry'
    | '/api/leads/documents/$documentId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadsUploadRoute: typeof LeadsUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLeadsUploadRoute: typeof ApiLeadsUploadRoute
  ApiLeadsDocumentsDocumentIdRetryRoute: typeof ApiLeadsDocumentsDocumentIdRetryRoute
  ApiLeadsDocumentsDocumentIdStatusRoute: typeof ApiLeadsDocumentsDocumentIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/upload': {
      id: '/leads/upload'
      path: '/leads/upload'
      fullPath: '/leads/upload'
      preLoaderRoute: typeof LeadsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/upload': {
      id: '/api/leads/upload'
      path: '/api/leads/upload'
      fullPath: '/api/leads/upload'
      preLoaderRoute: typeof ApiLeadsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/documents/$documentId/status': {
      id: '/api/leads/documents/$documentId/status'
      path: '/api/leads/documents/$documentId/status'
      fullPath: '/api/leads/documents/$documentId/status'
      preLoaderRoute: typeof ApiLeadsDocumentsDocumentIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/documents/$documentId/retry': {
      id: '/api/leads/documents/$documentId/retry'
      path: '/api/leads/documents/$documentId/retry'
      fullPath: '/api/leads/documents/$documentId/retry'
      preLoaderRoute: typeof ApiLeadsDocumentsDocumentIdRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadsUploadRoute: LeadsUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLeadsUploadRoute: ApiLeadsUploadRoute,
  ApiLeadsDocumentsDocumentIdRetryRoute: ApiLeadsDocumentsDocumentIdRetryRoute,
  ApiLeadsDocumentsDocumentIdStatusRoute:
    ApiLeadsDocumentsDocumentIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
